name: log_wrapper
description: logger wrapper for flutter
version: 1.0.4
homepage: https://github.com/flutter-packagist/log_wrapper

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.5.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
